module.exports={
  entry:'./app/app.jsx',
  output:{
    path:__dirname,
    filename:'./public/bundle.js'
  },
  resolve:{
    modules:[__dirname,
      'node_modules',
      './app/components'
    ],
    extensions:['.js','.jsx']
  },
  module:{
    loaders:[
      {
        loader:'babel-loader',
        query:{
          presets:['react','es2015','env','stage-0']
        },
        test: /\.jsx?$/,
        exclude:/(node_modules|bower_components)/
      }
    ]
  }
};
